[scenario01]

== Szenario 1

Im folgenden soll anhand eines einführenden Beispieles das Konzept der sog. Smart Contracts eingeführt werden.

=== Einfuehrung

Am Beispiel einer Sportwette sollen die Funktionsweise und die Eigenschaften eines Smart Contracts aufgezeigt werden. Anhand eines Fußballspiels kann eine Sportwette definiert werden. Ein Fußballspiel zwischen Mannschaft A und Mannschaft B kann generell drei Ergebnisse bzw. Endzustände aufweisen:

* Mannschaft A gewinnt und Mannschaft B verliert
* Mannschaft B gewinnt und Mannschaft A verliert
* das Spiel geht unentschieden aus

Um nun eine Wette auf eines der Ergebnisse abzugeben, würde normalerweiße ein sog. Buchmacher konsultiert. Dieser würde Wetten von unterschiedlichen Teilnehmern, mit unterschiedlichen Wetteinsätzen und natürlich unterschiedlichem Tipp entgegennehmen. Dies sollte klarerweise alles vor dem Start eines Fußballspiels geschehen. Aus den gesamten abgegebenen Wetten wird die sog. Gewinnquote berechnet. Diese Quote gibt an mit welchem Faktor der Wetteinsatz im Falle eines richtigen Tipps multipliziert wird. Aus der Quote errechnet sich somit der mögliche Gewinn für die Wettteilnehmer. In Tabelle 1 wird ein Beispiel eines möglichen Wettablaufs dargestellt. In diesem vereinfachten Beispiel ist davon auszugehen, dass keine Gebühren für den Buchmacher bzw. keine Steuern erhoben werden.

[cols="3,^2,^2,^2",options="header,footer"]
|=========================================================
|Ergebnis |kummulierte Einsätze | Prozent| Gewinnquote

|Mannschaft A gewinnt |€ 20.000 | 25% | 4
|Mannschaft B gewinnt |€ 50.000 | 62,5% | 1,6
|unentschieden |€ 10.000 | 12,5% | 8
|gesamt|€ 80.000| 100% | 

|=========================================================

Die Wettquote berechnet sich somit konkret über den gesamten Wetteinsatz dividiert durch die kummulierten Wetteinsätze aller Teilnehmer für den jeweiligen Tipp. Die Gewinnquote bedeutet somit für einen Wettteilnehmer, dass für jeden Euro der investiert wird das 4-, 1,6- bzw. 8-fache als Gewinn verbucht werden kann. An den Beispielzahlen ist zu erkennen, dass eine Gewinnquote immer größer als 1 sein muss, andernfalls würde die Teilnahme an einer Wette keinen Sinn machen. Zusätzlich ist zu sehen, dass der Tipp mit dem kleinsten kummulierten Wetteinsatz die höchste Gewinnchance bietet.

.Kollektive Intelligenz
[NOTE]
===============================
Wetten könnten auch als Vorhersagen betrachtet werden und die kummulierten Wetteinsätze als Eintrittswahrscheinlichkeit gedeutet werden. Im Beispiel der Fußballwette könnte dies so interpretiert werden, dass mit einer Wahrscheinlichkeit von 12,5% ein Unentschieden gespielt wird. Die Blockchainanwendung `augur` macht sich genau diesen Umstand zu nutze und bietet Vorhersagen der ``kollektiven Intelligenz'' als Dienstleistung an.
===============================
